import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "next.js13 Blog",
  description: "Generated by create next app",
};

// headerとfooterはどのページでも共通で持つので共通レイアウトのlayout.tsxで管理

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <Header />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
