import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "next.js13 Blog",
  description: "Generated by create next app",
};

// headerとfooterはどのページでも共通で持つので共通レイアウトのlayout.tsxで管理

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header className="text-red-300">Header</header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
